version: '3'
services:
  vnc-server:
    build: .
    ports:
      - "5901:5901"
      - "6080:6080"
      - "3000:3000"  # 添加Node.js服务器端口映射
    restart: unless-stopped
    volumes:
      - ./server:/server
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: >
      bash -c "
        # 创建VNC密码文件目录
        mkdir -p /root/.vnc &&
        echo 'password' | vncpasswd -f > /root/.vnc/passwd &&
        chmod 777 /root/.vnc/passwd &&
        
        # 使用supervisord管理服务
        supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "